name: Trigger Knit
on:
  workflow_dispatch:
  push:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: start-update
        uses: ./.github/actions/update-knit
        with:
          repo-token: ${{secrets.G_ACCESS_TOKEN}}
          owner: "facebook"
          released_repo: "react"
